version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.4-node-browsers

    steps:
      - checkout

      - run:
          name: "Prepare Environment"
          command: |
            sudo apt update
            sudo docker-php-ext-install zip

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: "Install Dependencies"
          command: composer install --dev --no-interaction

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      
      - run:
          name: "Build dir"
          command: mkdir -p build/logs

      # run tests with phpunit
      - run:
          name: "Run Unit Tests"
          command: XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover clover.xml

      # coveralls
      - run:
          name: "Coveralls"
          command: vendor/bin/php-coveralls --coverage_clover clover.xml
